### ISSUE TITLE
Find a name for award

### ISSUE THREAD

**Issue by sypets** [sypets/typo3-extension-documentation-award#6]
"extension documentation contest" is a bit long. Find a name which can be used in announcements and in prices etc.

Also a hashtag (e.g. like `#t3dd` for developer days etc.)

Ideally, something catchy like "Hacktoberfest".

## tools:

find names

* https://namelix.com/app/?keywords=typo3+extension+documentation+contest
* https://novanym.com/search?type=product&q=typo3+extension+documentation+contest+community+inspire+share+vote
* https://www.namesnack.com/app/business-name-generator/typo3%20extension%20documentation%20contest%20community%20inspire%20share%20vote/brand/ujwhcbbgu9e

logo maker

* https://www.zarla.com/logo-maker

**Comment by sypets** [comment]
## word association

* contest, award, competition
* nominate, voting
* TYPO3
* documentation
* extension
* community
* inspire
* collaborate

## find a motto

* "polish up documentation": clean, spring cleaning (however, we already have "sweeping week")
* collaborate, share, help each other
* clarity 
* inspiration, idea (lightbulb)

**Comment by sypets** [comment]
## possible names names + hashtags

* docoquest ("quest" aka search)
* extoquest
* extodoc (extension + documentation)
* docufy
* t3edc (hashtag for extension documentation contest)
* community power
* docinator
* docalizer
* shareversity
* extelligent
* extradocinary
* excellebrate (extension, excel + celebrate)
* extellebrate (extension + celebrate)
* dockety doop (name has a "ring" to it, e.g. like "zippety poop" or "hockee boo", dockety is a fictional word construction from doc for documentation, is also a common last name)
* dockety doozy ([doozie / doozy](https://www.merriam-webster.com/dictionary/doozy) = "an extraordinary one of its kind")
* Dockety dip
* Dockadoo
* Doc It!
* Kaspar's Krew (intentional typo, =crew)
* Kaspar's Kuest (intentional typo, = quest)
* The typo brigade
* clickdoc
* docshot
* Inspire to doc
* doc with us
* doc it up
* Think Docs

**Comment by sypets** [comment]
brainstorming from marketing team:

- Doc.On
- TopDoc Award, Top X Award
- EliteDocs Prize, TipTopDocs
- Documentation Achievement Award
- Extension Achievement Award
- Lifetime Achievement Award
- Community Achievement Awards
- New Extension Achievement Award -- otherwise we recognize the same, most popular extension every year...
- Young Developer Achievement Award
- TYPO3 Excellent Achievement Award
- Debugging Achievement Award
- Security Achievement Award

----

As noted:

> An **award** is usually given for some kind of excellence, while a **contest** can be more negative (i.e. a struggle).

So "**award**" should be used, rather than "contest".

About 

> otherwise we recognize the same, most popular extension every year...

That is a good point to not look at the current state, but look at the achievement. However we need to establish a baseline to see achievement.

**Comment by sypets** [comment]
My choice currently: 

**Extension Award - TopDoc**

This is a 2-part name. The left side "_Extension Award_" stays the same. The right side ("_TopDoc_") could vary each year (or for each LTS).

The "Extension Award" could be done every year (or for every LTS), but could have different focus, e.g. _documentation_, _testing_, _usability_, _accessability_, _security_ and there could even be different categories, e.g. "newcomer", "community choice", "achievement" (biggest improvement) etc.

**Comment by mabolek** [comment]
@sypets 

I think Extension Award and your reasoning behind it is good.

I think it should be Extension Award—Documentation or Extension Award—Best Documentation.


Though TopDoc is cool, seems to be a popular product name in the health sector, so tagging with #TopDoc in social media might not be as good as #T3ExtensionAward #documentation. That would also avoid having to come up with a special name for other types of awards.

**Comment by sypets** [comment]
used: [Extension Award for Documentation](https://typo3.org/article/extension-award-for-documentation-what-you-can-win)

even clearer is:

* **Extension Award for Best Documentation**
* hashtag: `#T3ExtensionAward`, `#T3ExtensionAward2021`
